name: Architect main Branch Deployment

on:
  push:
    branches:
      - main

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_BRANCH: true
  COMPONENT_FILE_PATH: architect.yml
  ARCHITECT_ACCOUNT: shreeniteam
  COMPONENT_NAME: springbootemplate
  ENVIRONMENT_NAME: shree
  BRANCH_NAME: main
  CLUSTER_NAME: architect
  ARC_NO_CACHE: 1

jobs:
  architect_create_branch_deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Version
        run: docker --version
      - name: docker available version
        run: apt-cache madison docker-ce | awk '{ print $3 }'
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          VERSION_STRING=5:23.0.0-1~ubuntu.22.04~jammy
          sudo apt-get remove docker-compose-plugin
          sudo apt-get remove docker-buildx-plugin
          sudo rm -f /usr/local/bin/docker-compose
          sudo apt-get --allow-downgrades install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin
          sudo apt-get --allow-downgrades install docker-compose-plugin=2.21.0-1~ubuntu.22.04~jammy
          #sudo curl -L "https://github.com/docker/compose/releases/download/2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: crazy-max/ghaction-github-runtime@v2 # Exports internal envs for Github Actions. Required for register caching to work.
      - name: Install Architect CLI
        run: npm install -g @architect-io/cli
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }} # These secrets were created on your behalf
      - name: docker compose
        run: docker compose version
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest
      - name: An environment created automatically by a GitHub branch workflow to facilitate automated component deployments
        run: architect environment:create --cluster=${{ env.CLUSTER_NAME }} --description="Architect workflow environment" ${{ env.ENVIRONMENT_NAME }}
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
